#+latex_class: sandy-article
#+latex_compiler: xelatex
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:t f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t num:nil
#+html_head: <link rel="stylesheet" href="https://sandyuraz.com/styles/org.min.css">
#+language: en

#+title: Homework 10 Oracle
#+subtitle: MATH 220 Spring 2021
#+author: Sandy Urazayev
#+date: 140; 12021 H.E.
#+email: University of Kansas (ctu@ku.edu)

Go back to the [[../../][home page]]

[[./index.pdf][[View the PDF version]​]]

Hi, this is the last oracle published (homework 11 was published first because
it had material used in the final exam). Instead of detailed solutions, we shall
limit ourselves to just answers in this oracle. Thanks

* Section 7.8
** Problem 1
*** Statement
    \begin{equation*}
 \mathbf{x}^{\prime}=\left(\begin{array}{ll}
 3 & -4 \\
 1 & -1
 \end{array}\right) \mathbf{x}
 \end{equation*}
*** Answer
    \begin{equation*}
\mathbf{x}=c_{1}\left(\begin{array}{l}
2 \\
1
\end{array}\right) e^{t}+c_{2}\left(\left(\begin{array}{l}
2 \\
1
\end{array}\right) t e^{t}+\left(\begin{array}{l}
1 \\
0
\end{array}\right) e^{t}\right)
\end{equation*}
** Problem 3
*** Statement
    \begin{equation*}
\mathbf{x}^{\prime}=\left(\begin{array}{rr}
-\frac{3}{2} & 1 \\
-\frac{1}{4} & -\frac{1}{2}
\end{array}\right) \mathbf{x}
\end{equation*}
*** Answer
    \begin{equation*}
\mathbf{x}=c_{1}\left(\begin{array}{l}
2 \\
1
\end{array}\right) e^{-t}+c_{2}\left(\left(\begin{array}{l}
2 \\
1
\end{array}\right) t e^{-t}+\left(\begin{array}{l}
0 \\
2
\end{array}\right) e^{-t}\right)
\end{equation*}
** Problem 8 (this is graded)
*** Statement
    \begin{equation*}
\mathbf{x}^{\prime}=\left(\begin{array}{rr}
3 & 9 \\
-1 & -3
\end{array}\right) \mathbf{x}, \quad \mathbf{x}(0)=\left(\begin{array}{l}
2 \\
4
\end{array}\right)
\end{equation*}
*** Answer
    \begin{equation*}
\mathbf{x}=2\left(\begin{array}{l}
1 \\
2
\end{array}\right)+14\left(\begin{array}{r}
3 \\
-1
\end{array}\right) t
\end{equation*}
** Problem 9(a)
*** Statement
    \begin{equation*}
\mathbf{x}^{\prime}=\left(\begin{array}{rrr}
1 & 0 & 0 \\
-4 & 1 & 0 \\
3 & 6 & 2
\end{array}\right) \mathbf{x}, \quad \mathbf{x}(0)=\left(\begin{array}{r}
-1 \\
2 \\
-30
\end{array}\right)
\end{equation*}
*** Answer
    \begin{equation*}
\mathbf{x}=\left(\begin{array}{r}
-1 \\
2 \\
-33
\end{array}\right) e^{t}+4\left(\begin{array}{r}
0 \\
1 \\
-6
\end{array}\right) t e^{t}+3\left(\begin{array}{l}
0 \\
0 \\
1
\end{array}\right) e^{2 t}
\end{equation*}
** Problem 10(a)
*** Statement
    \begin{equation*}
\mathbf{x}^{\prime}=\left(\begin{array}{rrr}
-\frac{5}{2} & 1 & 1 \\
1 & -\frac{5}{2} & 1 \\
1 & 1 & -\frac{5}{2}
\end{array}\right) \mathbf{x}, \quad \mathbf{x}(0)=\left(\begin{array}{r}
2 \\
3 \\
-1
\end{array}\right)
\end{equation*}
*** Answer
\begin{equation*}
\mathbf{x}=\frac{4}{3}\left(\begin{array}{l}
1 \\
1 \\
1
\end{array}\right) e^{-t / 2}+\frac{1}{3}\left(\begin{array}{r}
2 \\
5 \\
-7
\end{array}\right) e^{-7 t / 2}
\end{equation*}
* Section 6.1
** Problem 5
*** Statement
Find the Laplace transform of $f(t)=\cos (a t)$, where $a$ is a real
constant.
Recall that
\begin{equation*}
\cosh (b t)=\frac{1}{2}\left(e^{b t}+e^{-b t}\right) \text { and } \sinh (b t)=\frac{1}{2}\left(e^{b t}-e^{-b t}\right)
\end{equation*}
*** Answer
    \begin{equation*}
F(s)=\frac{s}{s^{2}+a^{2}}, \quad s>0
\end{equation*}
** Problem 7 (this is graded)
*** Statement
In each of Problems 6 through 7, use the linearity of the Laplace transform to
find the Laplace transform of the given function; $a$ and $b$ are real
constants. 
    
    \begin{equation*}
f(t)=\sinh (b t)
\end{equation*}
*** Answer
    \begin{equation*}
F(s)=\frac{b}{s^{2}-b^{2}}, \quad s>|b|
\end{equation*}
** Problem 12
*** Statement
In each of Problems 12 through 15, use integration by parts to find the Laplace
transform of the given function; $n$ is a positive integer and $a$ is a real
constant 
    
    \begin{equation*}
f(t)=t e^{a t}
\end{equation*}
*** Answer
    \begin{equation*}
F(s)=\frac{1}{(s-a)^{2}}, \quad s>a
\end{equation*}
    
